version: '3.7'

services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    restart: on-failure
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - certs:/certs/client
      - data:/var/jenkins_home
    networks:
      jenkins-net:
        aliases:
          - docker

  jenkins-blueocean:
    image: jenkinsci/blueocean
    privileged: false
    restart: on-failure
    depends_on:
      - jenkins-docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - certs:/certs/client:ro
      - data:/var/jenkins_home
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        protocol: tcp
        mode: host
    networks:
      jenkins-net:

volumes:
  certs:
  data:

networks:
  jenkins-net:
    driver: bridge

